name = "NetSurvival"
uuid = "8f9d5d0e-dd2e-4568-92d4-f8c5d34f25cf"
authors = ["Oskar Laverny <oskar.laverny@univ-amu.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
